spring.application.name=social

spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:43975/railway
spring.datasource.username=postgres
spring.datasource.password=rBTEnWdbbfCVGtJTbxWAMwqqfjQHlbgX
spring.datasource.sriver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.poperties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=XlzdOdRN9qSeXDzIyMs2Vq/XzlRqwD8Tp2hLQcFMLuI=

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE